name: xhs-gentle
on:
  workflow_dispatch:
    inputs:
      max_items:
        description: "每个关键词最多抓取多少条"
        required: false
        default: "5"
  # schedule:
  #   - cron: "15 7 * * *"   # 定时任务需要时再开

jobs:
  crawl-and-ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python & uv
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install -U uv

      - name: Sync deps
        run: uv pip install -r requirements.txt

      - name: Install Playwright
        run: uv run python -m playwright install --with-deps

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Restore cookie file from secret
        env:
          XHS_COOKIES_B64: ${{ secrets.XHS_COOKIES_B64 }}
        run: |
          echo "$XHS_COOKIES_B64" | base64 -d > $RUNNER_TEMP/xhs_cookies.json
          test -s $RUNNER_TEMP/xhs_cookies.json
          echo "Cookie file ready:"
          head -n 5 $RUNNER_TEMP/xhs_cookies.json

      - name: Gentle crawl
        env:
          XHS_COOKIES_PATH: ${{ runner.temp }}/xhs_cookies.json
          XHS_SAVE: sqlite
          XHS_LOGIN_TYPE: cookie
          PW_CHROMIUM_NO_SANDBOX: 1
        run: |
          xvfb-run -a uv run python throttle_xhs.py --max_items ${{ github.event.inputs.max_items }}

      - name: Ingest to Supabase
        if: success()
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          uv run python ingest_to_supabase.py
